spring.application.name=user_api_service
server.port=8081
dms.administration.service.url=http://localhost:8080
dms.administration.token=initial_password
dms.administration.whitelist=/api/v1/admin/user/login,/api/v1/admin/user/.*,/api/v1/admin/.*
mds.discovery.zookeeper.base-path=/discovery
mds.discovery.zookeeper.service-name=CLIENT_API
mds.discovery.zookeeper.session-timeout-ms=600000
mds.discovery.zookeeper.zookeeper-host=localhost:32181
mds.discovery.type=ZOOKEEPER
