spring.application.name=user_api_service
server.port=8081
dms.administration.service.url=http://localhost:8080
dms.administration.token=initial_password
dms.administration.whitelist=/api/v1/admin/user/login,/api/v1/admin/user/login1
