spring.application.name=data-managment-service
server.port=8082

dms.administration.service.url=http://localhost:8080
dms.administration.token=initial_password
dms.administration.whitelist=/api/v1/.*

spring.datasource.url=jdbc:postgresql://localhost:54346/postgres
spring.datasource.password=password
spring.datasource.username=user
spring.data.jdbc.dialect=postgresql

dms.kafka.bootstrap.servers=localhost:9091,localhost:9092,localhost:9093

spring.flyway.table=flyway_schema_history_datamanagement
spring.flyway.baseline-on-migrate=true

dms.fulltext.solr.zookeeperProperties.zkHosts=localhost:2181,localhost:2182,localhost:2183

dms.service.discovery.FULL_TEXT=http://localhost:8083
dms.service.discovery.ARCHIVE=http://localhost:8084
dms.service.discovery.MONITORING=http://localhost:8085

dms.user.admin.username=testUser
dms.user.admin.password=password

dms.archive.hdfs.base-path=archive
dms.archive.hdfs.hostname=hdfs://localhost:9000
dms.archive.hdfs.user=archive_service

mds.monitoring.influx.url=http://localhost:8886
mds.monitoring.influx.username=admin
mds.monitoring.influx.password=password

mds.discovery.zookeeper.base-path=/discovery
mds.discovery.zookeeper.service-name=DATA_MANAGEMENT
mds.discovery.zookeeper.session-timeout-ms=600000
mds.discovery.zookeeper.zookeeper-host=localhost:32181
mds.discovery.type=ZOOKEEPER




