library.mds.username=library_user
library.mds.password=qwe123
library.mds.url=http://localhost:8081
spring.application.name=library-app
library.task.project-id=3
library.task.task-name=books
server.port=12213
