package ru.spbstu.rakitin.dto;

public enum PermissionTypeEnum {
    FULL_TEXT_CREATE_TASK,
    FULL_TEXT_MANAGE_TASK,
    ARCHIVE_CREATE_TASK,
    MONITORING_CREATE_TASK,
    FULL_TEXT_VIEW_TASK,
    ARCHIVE_VIEW_TASK,
    MONITORING_VIEW_TASK,
    MONITORING_CREATE_API_KEY,
    CREATOR,
    TOPIC_CREATE,
    ARCHIVE_MANAGE_TASK,
    MONITORING_MANAGE_TASK,
    TOPIC_VIEW, ANY


}
